
/**:
  ros__parameters:
    robot_description_kinematics:
      iiwa:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3
      gripper:
        kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
        kinematics_solver_search_resolution: 0.0050000000000000001
        kinematics_solver_timeout: 0.0050000000000000001
